"""empty message

Revision ID: 2eae8d50daee
Revises: None
Create Date: 2016-02-21 11:12:21.055618

"""

# revision identifiers, used by Alembic.
revision = '2eae8d50daee'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed')
    ### end Alembic commands ###
