"""empty message

Revision ID: 31001493ae51
Revises: 2eae8d50daee
Create Date: 2016-02-21 22:24:39.009038

"""

# revision identifiers, used by Alembic.
revision = '31001493ae51'
down_revision = '2eae8d50daee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readingsession', sa.Column('completed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('readingsession', 'completed')
    ### end Alembic commands ###
